**Pandas Library Tutorial for Beginners**

In [ ]:
# ============================================
# PANDAS LIBRARY TUTORIAL FOR BEGINNERS
# Petrophysical Data Edition
# ============================================

import pandas as pd
import numpy as np

print("=" * 60)
print("PANDAS LIBRARY TUTORIAL FOR BEGINNERS")
print("Petrophysical Data: Porosity, Permeability, Formation")
print("=" * 60)

============================================================
PANDAS LIBRARY TUTORIAL FOR BEGINNERS
Petrophysical Data: Porosity, Permeability, Formation
============================================================

In [ ]:

# --------------------------------------------
# 1. IMPORTING PANDAS
# --------------------------------------------
print("\n1. IMPORTING PANDAS")
print("-" * 40)
# Convention: import pandas as pd
print("import pandas as pd")

1. IMPORTING PANDAS
----------------------------------------
import pandas as pd

In [29]:
#reading well
df_volve= pd.read_csv('15_9-F-1A.LAS.csv')

In [30]:
df_volve.head()

,DEPTH,ABDCQF01,ABDCQF02,ABDCQF03,ABDCQF04,BS,CALI,DRHO,DT,DTS,GR,NPHI,PEF,RACEHM,RACELM,RHOB,ROP,RPCEHM,RPCELM,RT
0,145.9,NaN,NaN,NaN,NaN,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,146.0,NaN,NaN,NaN,NaN,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,146.1,NaN,NaN,NaN,NaN,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,146.2,NaN,NaN,NaN,NaN,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,146.3,NaN,NaN,NaN,NaN,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
df_volve.tail()

,DEPTH,ABDCQF01,ABDCQF02,ABDCQF03,ABDCQF04,BS,CALI,DRHO,DT,DTS,GR,NPHI,PEF,RACEHM,RACELM,RHOB,ROP,RPCEHM,RPCELM,RT
35356,3681.5,NaN,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.6860,NaN,NaN,NaN
35357,3681.6,NaN,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.6826,NaN,NaN,NaN
35358,3681.7,NaN,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.7451,NaN,NaN,NaN
35359,3681.8,NaN,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.8076,NaN,NaN,NaN
35360,3681.9,NaN,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.4696,NaN,NaN,NaN

In [33]:
df_volve.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35361 entries, 0 to 35360
Data columns (total 20 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DEPTH     35361 non-null  float64
 1   ABDCQF01  10502 non-null  float64
 2   ABDCQF02  10502 non-null  float64
 3   ABDCQF03  10502 non-null  float64
 4   ABDCQF04  10504 non-null  float64
 5   BS        35361 non-null  float64
 6   CALI      10745 non-null  float64
 7   DRHO      10647 non-null  float64
 8   DT        10224 non-null  float64
 9   DTS       10214 non-null  float64
 10  GR        34671 non-null  float64
 11  NPHI      10524 non-null  float64
 12  PEF       10551 non-null  float64
 13  RACEHM    34211 non-null  float64
 14  RACELM    34211 non-null  float64
 15  RHOB      10551 non-null  float64
 16  ROP       34477 non-null  float64
 17  RPCEHM    34211 non-null  float64
 18  RPCELM    34211 non-null  float64
 19  RT        34211 non-null  float64
dtypes: float64(20)
memory usage: 5.4 MB

In [38]:
df_volve=df_volve.dropna()
df_volve

,DEPTH,ABDCQF01,ABDCQF02,ABDCQF03,ABDCQF04,BS,CALI,DRHO,DT,DTS,GR,NPHI,PEF,RACEHM,RACELM,RHOB,ROP,RPCEHM,RPCELM,RT
24739,2619.8,2.5538,2.5712,2.5055,2.5014,8.5,8.5000,0.0486,87.3753,181.3741,48.4883,0.2229,7.2445,1.0050,0.8472,2.4901,13.8923,1.9548,1.3111,1.9548
24740,2619.9,2.5862,2.5705,2.5124,2.5291,8.5,8.5000,0.0648,86.7117,181.2219,49.9066,0.2333,7.2138,1.0786,0.8462,2.5158,13.7831,2.3321,1.4104,2.3321
24741,2620.0,2.6059,2.5383,2.4906,2.5423,8.5,8.5001,0.0798,86.0484,181.0697,48.4469,0.2479,7.0271,1.1140,0.8361,2.5199,6.5390,2.6895,1.4836,2.6895
24742,2620.1,2.6061,2.4878,2.4524,2.5420,8.5,8.5233,0.0881,85.5393,180.8952,51.7540,0.2613,6.7356,1.1309,0.8232,2.5033,6.5414,2.6885,1.4956,2.6885
24743,2620.2,2.5830,2.4354,2.4148,2.5326,8.5,8.5000,0.0882,85.2690,180.6865,53.4699,0.2776,6.4257,1.1926,0.8138,2.4735,6.5439,2.4076,1.4650,2.4076
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34955,3641.4,2.6299,2.6227,2.6384,2.6210,8.5,8.6719,0.0555,74.0343,131.1953,120.1702,0.2050,7.1941,2.5454,2.4846,2.6282,11.2947,2.6042,2.5368,2.6042
34956,3641.5,2.6328,2.6294,2.6411,2.6239,8.5,8.6602,0.0582,74.1741,131.6474,121.1039,0.2036,7.1741,2.5659,2.4946,2.6320,11.2395,2.5379,2.5156,2.5379
34957,3641.6,2.6337,2.6356,2.6420,2.6260,8.5,8.6602,0.0606,74.3111,132.0925,120.5899,0.2009,7.1429,2.5670,2.4968,2.6344,11.1842,2.5140,2.5115,2.5140
34958,3641.7,2.6322,2.6382,2.6401,2.6255,8.5,8.6719,0.0616,74.4395,132.4320,120.4854,0.1973,7.0911,2.5716,2.5090,2.6337,11.1291,2.4805,2.5011,2.4805
34959,3641.8,2.6271,2.6350,2.6359,2.6232,8.5,8.6719,0.0611,74.5584,132.6560,120.2856,0.1930,7.0064,2.5665,2.5157,2.6295,11.0864,2.4754,2.5028,2.4754

In [37]:
df_volve.shape

(10136, 20)

In [39]:
df_volve.describe()

,DEPTH,ABDCQF01,ABDCQF02,ABDCQF03,ABDCQF04,BS,CALI,DRHO,DT,DTS,GR,NPHI,PEF,RACEHM,RACELM,RHOB,ROP,RPCEHM,RPCELM,RT
count,10136.000000,10136.000000,10136.000000,10136.000000,10136.000000,10136.0,10136.000000,10136.000000,10136.000000,10136.000000,10136.000000,10136.000000,10136.000000,10136.000000,10136.000000,10136.000000,10136.000000,10136.000000,10136.000000,10136.000000
mean,3127.025178,2.481719,2.485743,2.489006,2.484487,8.5,8.608592,0.050285,76.666650,140.418613,47.465318,0.167564,6.835434,3.615183,3.510110,2.483231,24.404270,9.533718,3.137955,9.533718
std,293.367267,0.140197,0.141851,0.144456,0.140998,0.0,0.043503,0.009827,12.866803,25.825765,64.093606,0.098980,1.076780,54.774291,31.539614,0.141106,6.875843,480.099916,2.958894,480.099916
min,2619.800000,1.933100,1.952400,1.942200,1.967300,8.5,8.468800,-0.023200,56.382300,96.900700,1.041600,0.029000,4.297800,0.197400,0.234900,1.980600,0.005100,0.142500,0.128200,0.142500
25%,2873.175000,2.408475,2.411875,2.413200,2.411475,8.5,8.578100,0.045400,67.818725,121.921200,11.271500,0.101400,6.093675,1.263750,1.174600,2.409600,20.820875,1.433550,1.310875,1.433550
50%,3126.550000,2.534800,2.540300,2.543300,2.539200,8.5,8.624900,0.049700,73.230600,133.169650,32.631150,0.141650,7.220900,2.599650,2.509500,2.537600,24.482950,2.944250,2.682650,2.944250
75%,3379.925000,2.580700,2.585500,2.590600,2.584125,8.5,8.625000,0.054900,82.713600,146.799425,49.946950,0.212000,7.703100,3.706150,3.442350,2.583000,27.393400,4.329425,3.836700,4.329425
max,3641.800000,3.164700,3.065600,3.268300,2.939700,8.5,8.874900,0.122500,116.231600,217.969900,587.017200,0.593200,10.758300,5464.369100,2189.603000,2.931500,44.343500,46224.449200,159.890700,46224.449200

In [41]:
df.columns

Index(['Formation_Name', 'Porosity', 'Permeability', 'Depth_m', 'K_Phi_Ratio',
       'Porosity_Fraction'],
      dtype='object')

In [42]:
df_volve.columns

Index(['DEPTH', 'ABDCQF01', 'ABDCQF02', 'ABDCQF03', 'ABDCQF04', 'BS', 'CALI',
       'DRHO', 'DT', 'DTS', 'GR', 'NPHI', 'PEF', 'RACEHM', 'RACELM', 'RHOB',
       'ROP', 'RPCEHM', 'RPCELM', 'RT'],
      dtype='object')

In [ ]:
#create a datframe

In [31]:
data_test={'Formation_nmae':['Sandstone_A', 'Shale_B', 'Limestone_C', 'Sandstone_D', 'Shale_E'],'Porosity': [22.5, 8.3, 18.7, 25.1, 6.2]}
df_test= pd.DataFrame(data_test)
df_test.head()

  Formation_nmae  Porosity
0    Sandstone_A      22.5
1        Shale_B       8.3
2    Limestone_C      18.7
3    Sandstone_D      25.1
4        Shale_E       6.2

In [ ]:
# --------------------------------------------
# 2. CREATING DATAFRAMES
# --------------------------------------------
print("\n2. CREATING DATAFRAMES")
print("-" * 40)

# From a dictionary - Petrophysical data
data = {
    'Formation_Name': ['Sandstone_A', 'Shale_B', 'Limestone_C', 'Sandstone_D', 'Shale_E'],
    'Porosity': [22.5, 8.3, 18.7, 25.1, 6.2],           # in %
    'Permeability': [150.0, 0.5, 45.0, 320.0, 0.2],     # in mD
    'Depth_m': [2500, 2510, 2520, 2530, 2540]           # depth in meters
}

df = pd.DataFrame(data)
print("DataFrame from dictionary (Petrophysical Data):")
print(df)
print()

# From a list of lists
data_list = [
    ['Sandstone_A', 22.5, 150.0, 2500],
    ['Shale_B', 8.3, 0.5, 2510],
    ['Limestone_C', 18.7, 45.0, 2520]
]
df_list = pd.DataFrame(data_list, columns=['Formation_Name', 'Porosity', 'Permeability', 'Depth_m'])
print("DataFrame from list of lists:")
print(df_list)
print()

2. CREATING DATAFRAMES
----------------------------------------
DataFrame from dictionary (Petrophysical Data):
  Formation_Name  Porosity  Permeability  Depth_m
0    Sandstone_A      22.5         150.0     2500
1        Shale_B       8.3           0.5     2510
2    Limestone_C      18.7          45.0     2520
3    Sandstone_D      25.1         320.0     2530
4        Shale_E       6.2           0.2     2540

DataFrame from list of lists:
  Formation_Name  Porosity  Permeability  Depth_m
0    Sandstone_A      22.5         150.0     2500
1        Shale_B       8.3           0.5     2510
2    Limestone_C      18.7          45.0     2520

In [ ]:
# --------------------------------------------
# 3. BASIC DATA INSPECTION
# --------------------------------------------
print("\n3. BASIC DATA INSPECTION")
print("-" * 40)

print("First 3 rows (head):")
print(df.head(3))
print()

print("Last 2 rows (tail):")
print(df.tail(2))
print()

print("DataFrame info:")
print(df.info())
print()

print("DataFrame shape (rows, columns):")
print(df.shape)
print()

print("Column names:")
print(df.columns)
print()

print("Data types:")
print(df.dtypes)
print()

print("Statistical summary:")
print(df.describe())
print()

3. BASIC DATA INSPECTION
----------------------------------------
First 3 rows (head):
  Formation_Name  Porosity  Permeability  Depth_m
0    Sandstone_A      22.5         150.0     2500
1        Shale_B       8.3           0.5     2510
2    Limestone_C      18.7          45.0     2520

Last 2 rows (tail):
  Formation_Name  Porosity  Permeability  Depth_m
3    Sandstone_D      25.1         320.0     2530
4        Shale_E       6.2           0.2     2540

DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Formation_Name  5 non-null      object
 1   Porosity        5 non-null      float64
 2   Permeability    5 non-null      float64
 3   Depth_m         5 non-null      int64
dtypes: float64(2), int64(1), object(1)
memory usage: 292.0+ bytes
None

DataFrame shape (rows, columns):
(5, 4)

Column names:
Index(['Formation_Name', 'Porosity', 'Permeability', 'Depth_m'], dtype='object')

Data types:
Formation_Name     object
Porosity          float64
Permeability      float64
Depth_m             int64
dtype: object

Statistical summary:
        Porosity  Permeability      Depth_m
count   5.000000       5.00000     5.000000
mean   16.160000     103.14000  2520.000000
std     8.478679     135.77186    15.811388
min     6.200000       0.20000  2500.000000
25%     8.300000       0.50000  2510.000000
50%    18.700000      45.00000  2520.000000
75%    22.500000     150.00000  2530.000000
max    25.100000     320.00000  2540.000000

In [48]:
df['QI']= df['Permeability']*df['Porosity']
df['QI']

0    3375.00
1       4.15
2     841.50
3    8032.00
4       1.24
Name: QI, dtype: float64

In [49]:
print("Select rows 1 to 3:")
print(df.iloc[1:4])
print()

Select rows 1 to 3:
  Formation_Name  Porosity  Permeability  Depth_m  K_Phi_Ratio  \
1        Shale_B       8.3           0.5     2510     0.060241
2    Limestone_C      18.7          45.0     2520     2.406417
3    Sandstone_D      25.1         320.0     2530    12.749004

   Porosity_Fraction       QI
1              0.083     4.15
2              0.187   841.50
3              0.251  8032.00

In [51]:
# Select by label (loc)
print("Select 'Porosity' column using loc:")
print(df.loc[:, 'Porosity'])
print()

Select 'Porosity' column using loc:
0    22.5
1     8.3
2    18.7
3    25.1
4     6.2
Name: Porosity, dtype: float64

In [50]:
df_volve.iloc[25:75]

,DEPTH,ABDCQF01,ABDCQF02,ABDCQF03,ABDCQF04,BS,CALI,DRHO,DT,DTS,GR,NPHI,PEF,RACEHM,RACELM,RHOB,ROP,RPCEHM,RPCELM,RT
24764,2622.3,2.2011,2.1750,2.1946,2.2038,8.5,8.5469,0.0479,90.7359,186.8835,42.3101,0.2559,4.8400,2.9537,0.3874,2.1913,6.5159,78.7557,1.6966,78.7557
24765,2622.4,2.2024,2.1743,2.1954,2.2051,8.5,8.5469,0.0468,90.9418,186.3483,41.9449,0.2587,4.8223,2.5914,0.4001,2.1917,6.5191,38.3718,1.6322,38.3718
24766,2622.5,2.2015,2.1763,2.1987,2.2063,8.5,8.5469,0.0462,91.1462,185.8179,41.0961,0.2630,4.8223,2.4854,0.4121,2.1933,6.5195,22.3927,1.6091,22.3927
24767,2622.6,2.2001,2.1803,2.2036,2.2067,8.5,8.5469,0.0463,91.4087,185.6696,41.1784,0.2663,4.8349,2.4840,0.4184,2.1959,6.5200,21.4846,1.6445,21.4846
24768,2622.7,2.2002,2.1854,2.2104,2.2074,8.5,8.5469,0.0476,91.6693,185.5222,41.5188,0.2664,4.8497,2.2506,0.4242,2.2000,6.5205,24.3846,1.6797,24.3846
24769,2622.8,2.2027,2.1907,2.2177,2.2082,8.5,8.5469,0.0493,91.9292,185.3748,41.6751,0.2635,4.8584,1.8957,0.4363,2.2048,6.5261,17.8654,1.6225,17.8654
24770,2622.9,2.2070,2.1963,2.2231,2.2093,8.5,8.5469,0.0510,91.9478,185.2192,42.5598,0.2605,4.8697,1.7529,0.4482,2.2091,6.5317,11.7504,1.5593,11.7504
24771,2623.0,2.2119,2.2031,2.2246,2.2105,8.5,8.5469,0.0524,91.9561,185.0632,41.6497,0.2604,4.8988,1.6786,0.4517,2.2123,6.5374,11.8207,1.5550,11.8207
24772,2623.1,2.2168,2.2102,2.2224,2.2110,8.5,8.5469,0.0534,91.9642,184.9073,42.1007,0.2629,4.9469,1.5899,0.4529,2.2140,6.5401,14.6322,1.5443,14.6322
24773,2623.2,2.2202,2.2150,2.2198,2.2105,8.5,8.5469,0.0542,91.8505,184.7774,43.6892,0.2645,4.9922,1.5399,0.4531,2.2145,6.5429,16.0918,1.4932,16.0918
24774,2623.3,2.2209,2.2158,2.2190,2.2084,8.5,8.5469,0.0539,91.7249,184.6501,43.7001,0.2619,5.0077,1.4633,0.4544,2.2136,6.5457,15.5279,1.4381,15.5279
24775,2623.4,2.2197,2.2142,2.2201,2.2047,8.5,8.5469,0.0523,91.5993,184.5224,43.8383,0.2547,4.9907,1.3375,0.4590,2.2122,6.5392,13.2960,1.3578,13.2960
24776,2623.5,2.2188,2.2140,2.2236,2.2020,8.5,8.5469,0.0498,91.4705,184.2686,44.0466,0.2453,4.9644,1.1950,0.4721,2.2125,6.5261,8.6246,1.2591,8.6246
24777,2623.6,2.2208,2.2179,2.2306,2.2030,8.5,8.5469,0.0474,91.3411,183.9948,45.4675,0.2372,4.9570,1.1337,0.4892,2.2166,6.5329,5.3746,1.1852,5.3746
24778,2623.7,2.2268,2.2257,2.2410,2.2086,8.5,8.5469,0.0463,91.2120,183.7213,45.6867,0.2340,4.9752,1.1155,0.5020,2.2247,6.5396,4.2264,1.1641,4.2264
24779,2623.8,2.2353,2.2347,2.2513,2.2166,8.5,8.5469,0.0467,91.1957,183.5993,45.6610,0.2368,4.9981,1.0973,0.5059,2.2335,6.5463,4.5446,1.1860,4.5446
24780,2623.9,2.2436,2.2410,2.2548,2.2229,8.5,8.5469,0.0482,91.2050,183.5115,43.2890,0.2431,4.9998,1.0976,0.4980,2.2386,6.5468,7.1255,1.2384,7.1255
24781,2624.0,2.2475,2.2413,2.2474,2.2242,8.5,8.5469,0.0494,91.2149,183.4236,42.1765,0.2491,4.9676,1.1034,0.4844,2.2365,6.5472,17.2238,1.3315,17.2238
24782,2624.1,2.2433,2.2346,2.2311,2.2202,8.5,8.5469,0.0491,91.4654,183.3106,41.8812,0.2529,4.9087,1.1146,0.4753,2.2274,6.5476,31.4569,1.3729,31.4569
24783,2624.2,2.2311,2.2233,2.2133,2.2137,8.5,8.5469,0.0475,91.7887,183.1901,40.5106,0.2543,4.8452,1.0920,0.4801,2.2154,6.5455,25.8240,1.3215,25.8240
24784,2624.3,2.2161,2.2129,2.2027,2.2090,8.5,8.5469,0.0459,92.1124,183.0695,40.1228,0.2542,4.8006,1.0043,0.4953,2.2066,6.5434,11.9662,1.2391,11.9662
24785,2624.4,2.2047,2.2078,2.2033,2.2089,8.5,8.5469,0.0458,92.6252,182.8828,41.0956,0.2549,4.7879,0.9229,0.5201,2.2046,6.5413,5.3241,1.1358,5.3241
24786,2624.5,2.2000,2.2083,2.2119,2.2127,8.5,8.5469,0.0474,93.2116,182.6706,40.3331,0.2591,4.8021,0.8873,0.5468,2.2081,6.5417,3.1260,1.0579,3.1260
24787,2624.6,2.2001,2.2118,2.2232,2.2175,8.5,8.5469,0.0498,93.7981,182.4580,40.1440,0.2681,4.8322,0.8899,0.5620,2.2135,6.5421,2.5675,1.0277,2.5675
24788,2624.7,2.2022,2.2152,2.2334,2.2211,8.5,8.5469,0.0522,94.3957,182.1187,40.2360,0.2807,4.8725,0.9149,0.5739,2.2183,6.5426,2.4201,1.0303,2.4201
24789,2624.8,2.2047,2.2166,2.2399,2.2237,8.5,8.5469,0.0532,94.9989,181.7175,41.3417,0.2954,4.9263,0.9417,0.5796,2.2214,6.5404,2.7120,1.0681,2.7120
24790,2624.9,2.2062,2.2158,2.2416,2.2265,8.5,8.5469,0.0508,95.6017,181.3165,41.2172,0.3102,5.0062,0.9485,0.5866,2.2229,6.5383,3.0884,1.1242,3.0884
24791,2625.0,2.2049,2.2172,2.2430,2.2305,8.5,8.5469,0.0455,96.0666,181.0786,42.6842,0.3223,5.1324,0.9532,0.6037,2.2259,6.5367,3.1174,1.1573,3.1174
24792,2625.1,2.2014,2.2265,2.2522,2.2388,8.5,8.5469,0.0407,96.4484,180.9388,46.3911,0.3282,5.3063,0.9503,0.6275,2.2347,6.7166,2.7222,1.1526,2.7222
24793,2625.2,2.2009,2.2455,2.2710,2.2540,8.5,8.5469,0.0391,96.8298,180.7996,50.9263,0.3269,5.5015,0.9449,0.6523,2.2513,6.8964,2.3180,1.1405,2.3180
24794,2625.3,2.2098,2.2710,2.2952,2.2757,8.5,8.5469,0.0408,97.0615,180.8927,59.5298,0.3214,5.6698,0.9423,0.6739,2.2731,7.0764,1.9740,1.1235,1.9740
24795,2625.4,2.2308,2.2943,2.3143,2.2988,8.5,8.5469,0.0445,97.1829,181.1568,65.8964,0.3148,5.7455,0.9416,0.6939,2.2937,7.2782,1.7043,1.0985,1.7043
24796,2625.5,2.2609,2.3082,2.3214,2.3157,8.5,8.5469,0.0472,97.3041,181.4215,68.4103,0.3086,5.7169,0.9537,0.7126,2.3073,7.6799,1.5395,1.0808,1.5395
24797,2625.6,2.2905,2.3113,2.3166,2.3243,8.5,8.5469,0.0476,97.3509,181.9447,67.4035,0.3038,5.6176,0.9540,0.7247,2.3123,7.8478,1.5141,1.0922,1.5141
24798,2625.7,2.3098,2.3078,2.3069,2.3270,8.5,8.5469,0.0462,97.3311,182.6991,66.1579,0.3010,5.5133,0.9521,0.7362,2.3115,8.0156,1.5718,1.1170,1.5718
24799,2625.8,2.3180,2.3049,2.2994,2.3279,8.5,8.5469,0.0449,97.3113,183.4537,64.3415,0.3009,5.4715,0.9608,0.7493,2.3099,8.1835,1.5999,1.1468,1.5999
24800,2625.9,2.3234,2.3059,2.2978,2.3290,8.5,8.5469,0.0445,97.3205,184.3431,64.1063,0.3031,5.5161,0.9761,0.7643,2.3107,8.3602,1.5664,1.1599,1.5664
24801,2626.0,2.3319,2.3100,2.3022,2.3300,8.5,8.5469,0.0454,97.3610,185.3786,64.7338,0.3058,5.6268,1.0095,0.7802,2.3150,8.5370,1.4696,1.1577,1.4696
24802,2626.1,2.3409,2.3158,2.3115,2.3319,8.5,8.5469,0.0473,97.4018,186.4142,66.1590,0.3069,5.7457,1.0289,0.7943,2.3214,8.7137,1.3698,1.1435,1.3698
24803,2626.2,2.3446,2.3214,2.3219,2.3350,8.5,8.5469,0.0489,97.5352,187.4737,66.5218,0.3064,5.8193,1.0305,0.8033,2.3271,8.8624,1.2924,1.1253,1.2924
24804,2626.3,2.3403,2.3250,2.3293,2.3383,8.5,8.5469,0.0499,97.7904,188.5645,67.8744,0.3063,5.8245,1.0320,0.8096,2.3300,9.0111,1.2427,1.1104,1.2427
24805,2626.4,2.3323,2.3239,2.3313,2.3414,8.5,8.5469,0.0500,98.0456,189.6551,67.9799,0.3094,5.7739,1.0410,0.8130,2.3292,9.1594,1.2037,1.0950,1.2037
24806,2626.5,2.3246,2.3190,2.3291,2.3428,8.5,8.5469,0.0492,98.3014,190.6765,66.6086,0.3152,5.7290,1.0147,0.8106,2.3260,9.1601,1.1782,1.0810,1.1782
24807,2626.6,2.3198,2.3173,2.3273,2.3408,8.5,8.5469,0.0478,98.5582,191.5867,64.3755,0.3206,5.7632,0.9751,0.8029,2.3239,9.1608,1.2094,1.0812,1.2094
24808,2626.7,2.3195,2.3242,2.3291,2.3368,8.5,8.5469,0.0466,98.8150,192.4967,62.9806,0.3220,5.8784,0.9624,0.7979,2.3256,9.1614,1.2508,1.0859,1.2508
24809,2626.8,2.3240,2.3376,2.3337,2.3347,8.5,8.5469,0.0469,99.0808,193.3534,61.8360,0.3180,6.0120,0.9608,0.7912,2.3311,9.1627,1.3000,1.0956,1.3000
24810,2626.9,2.3330,2.3522,2.3381,2.3372,8.5,8.5570,0.0492,99.3643,194.1047,61.0576,0.3095,6.1128,0.9644,0.7855,2.3385,9.1640,1.3360,1.1064,1.3360
24811,2627.0,2.3453,2.3634,2.3390,2.3440,8.5,8.5625,0.0529,99.6477,194.8560,61.5399,0.3034,6.1633,0.9850,0.7844,2.3452,9.1653,1.3232,1.1059,1.3232
24812,2627.1,2.3583,2.3676,2.3343,2.3512,8.5,8.5533,0.0564,99.8880,195.6060,66.3102,0.3014,6.1669,1.0141,0.7873,2.3484,9.1656,1.2913,1.1054,1.2913
24813,2627.2,2.3673,2.3624,2.3260,2.3529,8.5,8.5469,0.0576,100.0224,196.3527,68.4037,0.3021,6.1434,1.0313,0.7871,2.3461,9.1659,1.2999,1.1178,1.2999

In [ ]:
# --------------------------------------------
# 4. SELECTING DATA
# --------------------------------------------
print("\n4. SELECTING DATA")
print("-" * 40)

# Select a single column
print("Select 'Formation_Name' column:")
print(df['Formation_Name'])
print()

# Select multiple columns
print("Select 'Porosity' and 'Permeability' columns:")
print(df[['Porosity', 'Permeability']])
print()

# Select rows by index
print("Select row at index 2:")
print(df.iloc[2])
print()

# Select rows by range
print("Select rows 1 to 3:")
print(df.iloc[1:4])
print()

# Select by label (loc)
print("Select 'Porosity' column using loc:")
print(df.loc[:, 'Porosity'])
print()

4. SELECTING DATA
----------------------------------------
Select 'Formation_Name' column:
0    Sandstone_A
1        Shale_B
2    Limestone_C
3    Sandstone_D
4        Shale_E
Name: Formation_Name, dtype: object

Select 'Porosity' and 'Permeability' columns:
   Porosity  Permeability
0      22.5         150.0
1       8.3           0.5
2      18.7          45.0
3      25.1         320.0
4       6.2           0.2

Select row at index 2:
Formation_Name    Limestone_C
Porosity                 18.7
Permeability             45.0
Depth_m                  2520
Name: 2, dtype: object

Select rows 1 to 3:
  Formation_Name  Porosity  Permeability  Depth_m
1        Shale_B       8.3           0.5     2510
2    Limestone_C      18.7          45.0     2520
3    Sandstone_D      25.1         320.0     2530

Select 'Porosity' column using loc:
0    22.5
1     8.3
2    18.7
3    25.1
4     6.2
Name: Porosity, dtype: float64

In [52]:
df[df['Porosity'] > 20]

,Formation_Name,Porosity,Permeability,Depth_m,K_Phi_Ratio,Porosity_Fraction,QI
0,Sandstone_A,22.5,150.0,2500,6.666667,0.225,3375.0
3,Sandstone_D,25.1,320.0,2530,12.749004,0.251,8032.0

In [58]:
print(df[(df['Porosity'] > 15) & (df['Permeability'] == 150)])

  Formation_Name  Porosity  Permeability  Depth_m  K_Phi_Ratio  \
0    Sandstone_A      22.5         150.0     2500     6.666667

   Porosity_Fraction      QI
0              0.225  3375.0

In [ ]:
# --------------------------------------------
# 5. FILTERING DATA
# --------------------------------------------
print("\n5. FILTERING DATA")
print("-" * 40)

# Filter by condition - High porosity zones
print("Formations with Porosity > 20%:")
print(df[df['Porosity'] > 20])
print()

# Multiple conditions - Good reservoir quality
print("Formations with Porosity > 15% AND Permeability > 40 mD:")
print(df[(df['Porosity'] > 15) & (df['Permeability'] > 40)])
print()

# Filter by formation type
print("Sandstone and Limestone formations:")
print(df[df['Formation_Name'].str.contains('Sandstone|Limestone')])
print()

5. FILTERING DATA
----------------------------------------
Formations with Porosity > 20%:
  Formation_Name  Porosity  Permeability  Depth_m
0    Sandstone_A      22.5         150.0     2500
3    Sandstone_D      25.1         320.0     2530

Formations with Porosity > 15% AND Permeability > 40 mD:
  Formation_Name  Porosity  Permeability  Depth_m
0    Sandstone_A      22.5         150.0     2500
2    Limestone_C      18.7          45.0     2520
3    Sandstone_D      25.1         320.0     2530

Sandstone and Limestone formations:
  Formation_Name  Porosity  Permeability  Depth_m
0    Sandstone_A      22.5         150.0     2500
2    Limestone_C      18.7          45.0     2520
3    Sandstone_D      25.1         320.0     2530

In [59]:
# Calculate statistics
print(f"Average Porosity: {df['Porosity'].mean():.2f} %")
print(f"Maximum Permeability: {df['Permeability'].max():.2f} mD")
print(f"Minimum Permeability: {df['Permeability'].min():.2f} mD")
print(f"Total Depth Range: {df['Depth_m'].max() - df['Depth_m'].min()} m")
print()

Average Porosity: 16.16 %
Maximum Permeability: 320.00 mD
Minimum Permeability: 0.20 mD
Total Depth Range: 40 m

In [ ]:
# --------------------------------------------
# 6. BASIC OPERATIONS
# --------------------------------------------
print("\n6. BASIC OPERATIONS")
print("-" * 40)

# Add a new column - Permeability/Porosity ratio (quality indicator)
df['K_Phi_Ratio'] = df['Permeability'] / df['Porosity']
print("Added 'K_Phi_Ratio' column (Permeability/Porosity):")
print(df[['Formation_Name', 'Porosity', 'Permeability', 'K_Phi_Ratio']])
print()

# Modify existing column - Convert porosity from % to fraction
df['Porosity_Fraction'] = df['Porosity'] / 100
print("Added 'Porosity_Fraction' column (Porosity as decimal):")
print(df[['Porosity', 'Porosity_Fraction']])
print()

# Calculate statistics
print(f"Average Porosity: {df['Porosity'].mean():.2f} %")
print(f"Maximum Permeability: {df['Permeability'].max():.2f} mD")
print(f"Minimum Permeability: {df['Permeability'].min():.2f} mD")
print(f"Total Depth Range: {df['Depth_m'].max() - df['Depth_m'].min()} m")
print()

# Sort data
print("Sorted by Permeability (descending - best reservoirs first):")
print(df.sort_values('Permeability', ascending=False)[['Formation_Name', 'Permeability', 'Porosity']])
print()

6. BASIC OPERATIONS
----------------------------------------
Added 'K_Phi_Ratio' column (Permeability/Porosity):
  Formation_Name  Porosity  Permeability  K_Phi_Ratio
0    Sandstone_A      22.5         150.0     6.666667
1        Shale_B       8.3           0.5     0.060241
2    Limestone_C      18.7          45.0     2.406417
3    Sandstone_D      25.1         320.0    12.749004
4        Shale_E       6.2           0.2     0.032258

Added 'Porosity_Fraction' column (Porosity as decimal):
   Porosity  Porosity_Fraction
0      22.5              0.225
1       8.3              0.083
2      18.7              0.187
3      25.1              0.251
4       6.2              0.062

Average Porosity: 16.16 %
Maximum Permeability: 320.00 mD
Minimum Permeability: 0.20 mD
Total Depth Range: 40 m

Sorted by Permeability (descending - best reservoirs first):
  Formation_Name  Permeability  Porosity
3    Sandstone_D         320.0      25.1
0    Sandstone_A         150.0      22.5
2    Limestone_C          45.0      18.7
1        Shale_B           0.5       8.3
4        Shale_E           0.2       6.2

In [ ]:
# --------------------------------------------
# 7. HANDLING MISSING DATA
# --------------------------------------------
print("\n7. HANDLING MISSING DATA")
print("-" * 40)

# Create DataFrame with missing values (common in well logs)
data_missing = {
    'Formation_Name': ['Sandstone_A', 'Shale_B', 'Limestone_C', 'Sandstone_D'],
    'Porosity': [22.5, None, 18.7, 25.1],
    'Permeability': [150.0, 0.5, None, 320.0]
}
df_missing = pd.DataFrame(data_missing)
print("DataFrame with missing values (common in petrophysical logs):")
print(df_missing)
print()

# Check for missing values
print("Check for missing values:")
print(df_missing.isnull())
print()

print("Count of missing values per column:")
print(df_missing.isnull().sum())
print()

# Drop rows with missing values
print("Drop rows with missing values:")
print(df_missing.dropna())
print()

# Fill missing values
print("Fill missing values with 0 (not recommended for petrophysics):")
print(df_missing.fillna(0))
print()

print("Fill missing Porosity with mean porosity:")
mean_porosity = df_missing['Porosity'].mean()
print(df_missing.fillna({'Porosity': mean_porosity}))
print()

7. HANDLING MISSING DATA
----------------------------------------
DataFrame with missing values (common in petrophysical logs):
  Formation_Name  Porosity  Permeability
0    Sandstone_A      22.5         150.0
1        Shale_B       NaN           0.5
2    Limestone_C      18.7           NaN
3    Sandstone_D      25.1         320.0

Check for missing values:
   Formation_Name  Porosity  Permeability
0           False     False         False
1           False      True         False
2           False     False          True
3           False     False         False

Count of missing values per column:
Formation_Name    0
Porosity          1
Permeability      1
dtype: int64

Drop rows with missing values:
  Formation_Name  Porosity  Permeability
0    Sandstone_A      22.5         150.0
3    Sandstone_D      25.1         320.0

Fill missing values with 0 (not recommended for petrophysics):
  Formation_Name  Porosity  Permeability
0    Sandstone_A      22.5         150.0
1        Shale_B       0.0           0.5
2    Limestone_C      18.7           0.0
3    Sandstone_D      25.1         320.0

Fill missing Porosity with mean porosity:
  Formation_Name  Porosity  Permeability
0    Sandstone_A      22.5         150.0
1        Shale_B      22.1           0.5
2    Limestone_C      18.7           NaN
3    Sandstone_D      25.1         320.0

In [ ]:
# --------------------------------------------
# 8. GROUPING DATA
# --------------------------------------------
print("\n8. GROUPING DATA")
print("-" * 40)

# Add more data for better grouping example
data_group = {
    'Formation_Name': ['Sandstone_A', 'Shale_B', 'Limestone_C', 'Sandstone_D', 'Shale_E', 'Sandstone_F'],
    'Lithology': ['Sandstone', 'Shale', 'Limestone', 'Sandstone', 'Shale', 'Sandstone'],
    'Porosity': [22.5, 8.3, 18.7, 25.1, 6.2, 20.0],
    'Permeability': [150.0, 0.5, 45.0, 320.0, 0.2, 180.0]
}
df_group = pd.DataFrame(data_group)
print("DataFrame for grouping by Lithology:")
print(df_group)
print()

# Group by Lithology
print("Group by Lithology - Mean Porosity:")
print(df_group.groupby('Lithology')['Porosity'].mean())
print()

print("Group by Lithology - Multiple statistics:")
print(df_group.groupby('Lithology')['Permeability'].agg(['mean', 'sum', 'count']))
print()

print("Group by Lithology - Average Porosity & Permeability:")
print(df_group.groupby('Lithology')[['Porosity', 'Permeability']].mean())
print()

8. GROUPING DATA
----------------------------------------
DataFrame for grouping by Lithology:
  Formation_Name  Lithology  Porosity  Permeability
0    Sandstone_A  Sandstone      22.5         150.0
1        Shale_B      Shale       8.3           0.5
2    Limestone_C  Limestone      18.7          45.0
3    Sandstone_D  Sandstone      25.1         320.0
4        Shale_E      Shale       6.2           0.2
5    Sandstone_F  Sandstone      20.0         180.0

Group by Lithology - Mean Porosity:
Lithology
Limestone    18.700000
Sandstone    22.533333
Shale         7.250000
Name: Porosity, dtype: float64

Group by Lithology - Multiple statistics:
                 mean    sum  count
Lithology
Limestone   45.000000   45.0      1
Sandstone  216.666667  650.0      3
Shale        0.350000    0.7      2

Group by Lithology - Average Porosity & Permeability:
            Porosity  Permeability
Lithology
Limestone  18.700000     45.000000
Sandstone  22.533333    216.666667
Shale       7.250000      0.350000

In [ ]:
# --------------------------------------------
# 9. READING AND WRITING FILES
# --------------------------------------------
print("\n9. READING AND WRITING FILES")
print("-" * 40)

# Write to CSV
df.to_csv('petrophysical_data.csv', index=False)
print("DataFrame saved to 'petrophysical_data.csv'")

# Read from CSV
df_read = pd.read_csv('petrophysical_data.csv')
print("\nRead from 'petrophysical_data.csv':")
print(df_read)
print()

# Write to Excel (requires openpyxl)
# df.to_excel('petrophysical_data.xlsx', index=False)
# df_read_excel = pd.read_excel('petrophysical_data.xlsx')

# Write to JSON
df.to_json('petrophysical_data.json', orient='records')
print("DataFrame saved to 'petrophysical_data.json'")

# Read from JSON
df_read_json = pd.read_json('petrophysical_data.json')
print("\nRead from 'petrophysical_data.json':")
print(df_read_json)
print()

9. READING AND WRITING FILES
----------------------------------------
DataFrame saved to 'petrophysical_data.csv'

Read from 'petrophysical_data.csv':
  Formation_Name  Porosity  Permeability  Depth_m  K_Phi_Ratio  \
0    Sandstone_A      22.5         150.0     2500     6.666667
1        Shale_B       8.3           0.5     2510     0.060241
2    Limestone_C      18.7          45.0     2520     2.406417
3    Sandstone_D      25.1         320.0     2530    12.749004
4        Shale_E       6.2           0.2     2540     0.032258

   Porosity_Fraction
0              0.225
1              0.083
2              0.187
3              0.251
4              0.062

DataFrame saved to 'petrophysical_data.json'

Read from 'petrophysical_data.json':
  Formation_Name  Porosity  Permeability  Depth_m  K_Phi_Ratio  \
0    Sandstone_A      22.5         150.0     2500     6.666667
1        Shale_B       8.3           0.5     2510     0.060241
2    Limestone_C      18.7          45.0     2520     2.406417
3    Sandstone_D      25.1         320.0     2530    12.749004
4        Shale_E       6.2           0.2     2540     0.032258

   Porosity_Fraction
0              0.225
1              0.083
2              0.187
3              0.251
4              0.062

In [ ]:
# --------------------------------------------
# 10. USEFUL TIPS FOR PETROPHYSICAL DATA
# --------------------------------------------
print("\n10. USEFUL TIPS")
print("-" * 40)

print("✓ Use df.head() to quickly view well log data")
print("✓ Use df.info() to check data types and missing log values")
print("✓ Use df.describe() for statistical summary of porosity/permeability")
print("✓ Use df['Porosity'] to select a petrophysical property")
print("✓ Use df[df['Porosity'] > 20] to filter good reservoir zones")
print("✓ Use df.groupby('Lithology') for formation-based analysis")
print("✓ Use df.dropna() or df.fillna() for handling missing log data")
print("✓ Use df.to_csv() and pd.read_csv() for LAS/CSV file I/O")
print()

10. USEFUL TIPS
----------------------------------------
✓ Use df.head() to quickly view well log data
✓ Use df.info() to check data types and missing log values
✓ Use df.describe() for statistical summary of porosity/permeability
✓ Use df['Porosity'] to select a petrophysical property
✓ Use df[df['Porosity'] > 20] to filter good reservoir zones
✓ Use df.groupby('Lithology') for formation-based analysis
✓ Use df.dropna() or df.fillna() for handling missing log data
✓ Use df.to_csv() and pd.read_csv() for LAS/CSV file I/O

In [ ]:

# --------------------------------------------
# BONUS: PRACTICAL EXAMPLE - RESERVOIR QUALITY ANALYSIS
# --------------------------------------------
print("\n11. PRACTICAL EXAMPLE - RESERVOIR QUALITY ANALYSIS")
print("-" * 40)

reservoir_data = {
    'Well_ID': ['Well_A', 'Well_A', 'Well_B', 'Well_B', 'Well_C'],
    'Formation': ['Upper_Sand', 'Lower_Sand', 'Upper_Sand', 'Shale', 'Upper_Sand'],
    'Porosity': [24.0, 19.5, 22.0, 7.0, 26.0],
    'Permeability': [280.0, 95.0, 150.0, 0.3, 410.0],
    'Water_Saturation': [25.0, 35.0, 30.0, 85.0, 20.0]
}

df_reservoir = pd.DataFrame(reservoir_data)
print("Reservoir Data:")
print(df_reservoir)
print()

print("Average Porosity by Formation:")
print(df_reservoir.groupby('Formation')['Porosity'].mean())
print()

print("Average Permeability by Formation:")
print(df_reservoir.groupby('Formation')['Permeability'].mean())
print()

print("Reservoir Quality Classification (Porosity > 20% AND Perm > 100 mD):")
df_reservoir['Reservoir_Quality'] = np.where(
    (df_reservoir['Porosity'] > 20) & (df_reservoir['Permeability'] > 100),
    'Good', 'Poor'
)
print(df_reservoir[['Formation', 'Porosity', 'Permeability', 'Reservoir_Quality']])
print()

print("Best Reservoir Zone (Highest Permeability):")
print(df_reservoir.loc[df_reservoir['Permeability'].idxmax()])
print()

print("Flow Capacity Calculation (k*h, assuming 10m thickness):")
df_reservoir['Flow_Capacity'] = df_reservoir['Permeability'] * 10
print(df_reservoir[['Formation', 'Permeability', 'Flow_Capacity']])
print()

print("=" * 60)
print("TUTORIAL COMPLETED!")
print("=" * 60)

11. PRACTICAL EXAMPLE - RESERVOIR QUALITY ANALYSIS
----------------------------------------
Reservoir Data:
  Well_ID   Formation  Porosity  Permeability  Water_Saturation
0  Well_A  Upper_Sand      24.0         280.0              25.0
1  Well_A  Lower_Sand      19.5          95.0              35.0
2  Well_B  Upper_Sand      22.0         150.0              30.0
3  Well_B       Shale       7.0           0.3              85.0
4  Well_C  Upper_Sand      26.0         410.0              20.0

Average Porosity by Formation:
Formation
Lower_Sand    19.5
Shale          7.0
Upper_Sand    24.0
Name: Porosity, dtype: float64

Average Permeability by Formation:
Formation
Lower_Sand     95.0
Shale           0.3
Upper_Sand    280.0
Name: Permeability, dtype: float64

Reservoir Quality Classification (Porosity > 20% AND Perm > 100 mD):
    Formation  Porosity  Permeability Reservoir_Quality
0  Upper_Sand      24.0         280.0              Good
1  Lower_Sand      19.5          95.0              Poor
2  Upper_Sand      22.0         150.0              Good
3       Shale       7.0           0.3              Poor
4  Upper_Sand      26.0         410.0              Good

Best Reservoir Zone (Highest Permeability):
Well_ID                  Well_C
Formation            Upper_Sand
Porosity                   26.0
Permeability              410.0
Water_Saturation           20.0
Reservoir_Quality          Good
Name: 4, dtype: object

Flow Capacity Calculation (k*h, assuming 10m thickness):
    Formation  Permeability  Flow_Capacity
0  Upper_Sand         280.0         2800.0
1  Lower_Sand          95.0          950.0
2  Upper_Sand         150.0         1500.0
3       Shale           0.3            3.0
4  Upper_Sand         410.0         4100.0

============================================================
TUTORIAL COMPLETED!
============================================================

**NumPy Tutorial for Beginners**

In [ ]:
# ============================================
# NUMPY LIBRARY TUTORIAL FOR BEGINNERS
# Petrophysical Data Edition
# ============================================

import numpy as np

print("=" * 60)
print("NUMPY LIBRARY TUTORIAL FOR BEGINNERS")
print("Petrophysical Data: Porosity, Permeability, Formation")
print("=" * 60)

============================================================
NUMPY LIBRARY TUTORIAL FOR BEGINNERS
Petrophysical Data: Porosity, Permeability, Formation
============================================================

In [ ]:
# --------------------------------------------
# 1. IMPORTING NUMPY
# --------------------------------------------
print("\n1. IMPORTING NUMPY")
print("-" * 40)
# Convention: import numpy as np
print("import numpy as np")

1. IMPORTING NUMPY
----------------------------------------
import numpy as np

In [60]:
dfnum=df.to_numpy()
dfnum

array([['Sandstone_A', 22.5, 150.0, 2500, 6.666666666666667, 0.225,
        3375.0],
       ['Shale_B', 8.3, 0.5, 2510, 0.06024096385542168, 0.083, 4.15],
       ['Limestone_C', 18.7, 45.0, 2520, 2.4064171122994655, 0.187,
        841.5],
       ['Sandstone_D', 25.1, 320.0, 2530, 12.749003984063744, 0.251,
        8032.0],
       ['Shale_E', 6.2, 0.2, 2540, 0.03225806451612903, 0.062,
        1.2400000000000002]], dtype=object)

In [ ]:
# --------------------------------------------
# 2. CREATING NUMPY ARRAYS
# --------------------------------------------
print("\n2. CREATING NUMPY ARRAYS")
print("-" * 40)

# From a Python list - Petrophysical data
porosity = np.array([22.5, 8.3, 18.7, 25.1, 6.2])        # in %
permeability = np.array([150.0, 0.5, 45.0, 320.0, 0.2])  # in mD
depth = np.array([2500, 2510, 2520, 2530, 2540])         # in meters

print("Porosity array (%):")
print(porosity)
print()

print("Permeability array (mD):")
print(permeability)
print()

print("Depth array (m):")
print(depth)
print()

# Create array with specific values
formations = np.array(['Sandstone_A', 'Shale_B', 'Limestone_C',
                       'Sandstone_D', 'Shale_E'])
print("Formation names array:")
print(formations)
print()

# Create arrays using NumPy functions
print("Create array of zeros (5 elements):")
print(np.zeros(5))
print()

print("Create array of ones (5 elements):")
print(np.ones(5))
print()

print("Create array with range (depth intervals):")
print(np.arange(2500, 2550, 10))
print()

print("Create array with evenly spaced values (porosity range):")
print(np.linspace(0, 30, 6))  # 6 values from 0 to 30
print()

2. CREATING NUMPY ARRAYS
----------------------------------------
Porosity array (%):
[22.5  8.3 18.7 25.1  6.2]

Permeability array (mD):
[1.5e+02 5.0e-01 4.5e+01 3.2e+02 2.0e-01]

Depth array (m):
[2500 2510 2520 2530 2540]

Formation names array:
['Sandstone_A' 'Shale_B' 'Limestone_C' 'Sandstone_D' 'Shale_E']

Create array of zeros (5 elements):
[0. 0. 0. 0. 0.]

Create array of ones (5 elements):
[1. 1. 1. 1. 1.]

Create array with range (depth intervals):
[2500 2510 2520 2530 2540]

Create array with evenly spaced values (porosity range):
[ 0.  6. 12. 18. 24. 30.]

In [ ]:
# --------------------------------------------
# 3. ARRAY PROPERTIES
# --------------------------------------------
print("\n3. ARRAY PROPERTIES")
print("-" * 40)

print(f"Porosity array shape: {porosity.shape}")
print(f"Porosity array dimensions: {porosity.ndim}")
print(f"Porosity array data type: {porosity.dtype}")
print(f"Porosity array size (elements): {porosity.size}")
print()

print(f"Permeability array item size (bytes): {permeability.itemsize}")
print(f"Permeability array total bytes: {permeability.nbytes}")
print()

3. ARRAY PROPERTIES
----------------------------------------
Porosity array shape: (5,)
Porosity array dimensions: 1
Porosity array data type: float64
Porosity array size (elements): 5

Permeability array item size (bytes): 8
Permeability array total bytes: 40

In [ ]:
# --------------------------------------------
# 4. INDEXING AND SLICING
# --------------------------------------------
print("\n4. INDEXING AND SLICING")
print("-" * 40)

# Access single element
print(f"First porosity value: {porosity[0]} %")
print(f"Third permeability value: {permeability[2]} mD")
print()

# Access last element
print(f"Last depth value: {depth[-1]} m")
print()

# Slicing - get a range of values
print("Porosity values from index 1 to 3:")
print(porosity[1:4])
print()

print("Every second depth value:")
print(depth[::2])
print()

# Boolean indexing - filter by condition
print("Porosity values greater than 20%:")
print(porosity[porosity > 20])
print()

print("Formations with permeability > 50 mD:")
print(formations[permeability > 50])
print()

4. INDEXING AND SLICING
----------------------------------------
First porosity value: 22.5 %
Third permeability value: 45.0 mD

Last depth value: 2540 m

Porosity values from index 1 to 3:
[ 8.3 18.7 25.1]

Every second depth value:
[2500 2520 2540]

Porosity values greater than 20%:
[22.5 25.1]

Formations with permeability > 50 mD:
['Sandstone_A' 'Sandstone_D']

In [61]:
print("Permeability * 2 (double all values):")
print(permeability * 2)
print()

Permeability * 2 (double all values):
[3.0e+02 1.0e+00 9.0e+01 6.4e+02 4.0e-01]

In [62]:
print("Porosity / 100 (convert % to fraction):")
print(porosity / 100)
print()

Porosity / 100 (convert % to fraction):
[0.225 0.083 0.187 0.251 0.062]

In [ ]:
# --------------------------------------------
# 5. BASIC MATHEMATICAL OPERATIONS
# --------------------------------------------
print("\n5. BASIC MATHEMATICAL OPERATIONS")
print("-" * 40)

# Element-wise operations
print("Porosity + 5 (increase all values by 5%):")
print(porosity + 5)
print()

print("Permeability * 2 (double all values):")
print(permeability * 2)
print()

print("Porosity / 100 (convert % to fraction):")
print(porosity / 100)
print()

# Operations between arrays
print("Permeability / Porosity (K/φ ratio - quality indicator):")
k_phi_ratio = permeability / porosity
print(k_phi_ratio)
print()

# Power and square root
print("Porosity squared:")
print(porosity ** 2)
print()

print("Square root of permeability:")
print(np.sqrt(permeability))
print()

5. BASIC MATHEMATICAL OPERATIONS
----------------------------------------
Porosity + 5 (increase all values by 5%):
[27.5 13.3 23.7 30.1 11.2]

Permeability * 2 (double all values):
[3.0e+02 1.0e+00 9.0e+01 6.4e+02 4.0e-01]

Porosity / 100 (convert % to fraction):
[0.225 0.083 0.187 0.251 0.062]

Permeability / Porosity (K/φ ratio - quality indicator):
[ 6.66666667  0.06024096  2.40641711 12.74900398  0.03225806]

Porosity squared:
[506.25  68.89 349.69 630.01  38.44]

Square root of permeability:
[12.24744871  0.70710678  6.70820393 17.88854382  0.4472136 ]

In [63]:
print("\n6. STATISTICAL FUNCTIONS")
print("-" * 40)

print("=== POROSITY STATISTICS ===")
print(f"Mean: {np.mean(porosity):.2f} %")
print(f"Median: {np.median(porosity):.2f} %")
print(f"Standard Deviation: {np.std(porosity):.2f} %")
print(f"Min: {np.min(porosity)} %")
print(f"Max: {np.max(porosity)} %")
print(f"Sum: {np.sum(porosity):.2f} %")
print(f"Range: {np.ptp(porosity)} %")  # ptp = peak to peak
print()

6. STATISTICAL FUNCTIONS
----------------------------------------
=== POROSITY STATISTICS ===
Mean: 16.16 %
Median: 18.70 %
Standard Deviation: 7.58 %
Min: 6.2 %
Max: 25.1 %
Sum: 80.80 %
Range: 18.900000000000002 %

In [ ]:
# --------------------------------------------
# 6. STATISTICAL FUNCTIONS
# --------------------------------------------
print("\n6. STATISTICAL FUNCTIONS")
print("-" * 40)

print("=== POROSITY STATISTICS ===")
print(f"Mean: {np.mean(porosity):.2f} %")
print(f"Median: {np.median(porosity):.2f} %")
print(f"Standard Deviation: {np.std(porosity):.2f} %")
print(f"Min: {np.min(porosity)} %")
print(f"Max: {np.max(porosity)} %")
print(f"Sum: {np.sum(porosity):.2f} %")
print(f"Range: {np.ptp(porosity)} %")  # ptp = peak to peak
print()

print("=== PERMEABILITY STATISTICS ===")
print(f"Mean: {np.mean(permeability):.2f} mD")
print(f"Geometric Mean: {np.exp(np.mean(np.log(permeability[permeability > 0]))):.2f} mD")
print(f"Min: {np.min(permeability)} mD")
print(f"Max: {np.max(permeability)} mD")
print()

# Percentiles
print("Porosity percentiles:")
print(f"25th percentile: {np.percentile(porosity, 25):.2f} %")
print(f"50th percentile (median): {np.percentile(porosity, 50):.2f} %")
print(f"75th percentile: {np.percentile(porosity, 75):.2f} %")
print()

6. STATISTICAL FUNCTIONS
----------------------------------------
=== POROSITY STATISTICS ===
Mean: 16.16 %
Median: 18.70 %
Standard Deviation: 7.58 %
Min: 6.2 %
Max: 25.1 %
Sum: 80.80 %
Range: 18.900000000000002 %

=== PERMEABILITY STATISTICS ===
Mean: 103.14 mD
Geometric Mean: 11.67 mD
Min: 0.2 mD
Max: 320.0 mD

Porosity percentiles:
25th percentile: 8.30 %
50th percentile (median): 18.70 %
75th percentile: 22.50 %

In [64]:
# Reshape arrays
depth_2d = depth.reshape(5, 1)
print("Depth array reshaped to column vector (5x1):")
print(depth_2d)
print()

Depth array reshaped to column vector (5x1):
[[2500]
 [2510]
 [2520]
 [2530]
 [2540]]

In [66]:
more_porosity = np.array([21.0, 19.5])
combined_porosity = np.concatenate((porosity, more_porosity))
print("Combined porosity array:")
print(combined_porosity)
print()

Combined porosity array:
[22.5  8.3 18.7 25.1  6.2 21.  19.5]

In [65]:
# Stack arrays together
petro_data = np.column_stack((porosity, permeability, depth))
print("Stacked petrophysical data (Porosity, Permeability, Depth):")
print(petro_data)
print()

Stacked petrophysical data (Porosity, Permeability, Depth):
[[2.25e+01 1.50e+02 2.50e+03]
 [8.30e+00 5.00e-01 2.51e+03]
 [1.87e+01 4.50e+01 2.52e+03]
 [2.51e+01 3.20e+02 2.53e+03]
 [6.20e+00 2.00e-01 2.54e+03]]

In [ ]:
# --------------------------------------------
# 7. ARRAY MANIPULATION
# --------------------------------------------
print("\n7. ARRAY MANIPULATION")
print("-" * 40)

# Reshape arrays
depth_2d = depth.reshape(5, 1)
print("Depth array reshaped to column vector (5x1):")
print(depth_2d)
print()

# Stack arrays together
petro_data = np.column_stack((porosity, permeability, depth))
print("Stacked petrophysical data (Porosity, Permeability, Depth):")
print(petro_data)
print()

# Concatenate arrays
more_porosity = np.array([21.0, 19.5])
combined_porosity = np.concatenate((porosity, more_porosity))
print("Combined porosity array:")
print(combined_porosity)
print()

# Sort arrays
print("Porosity sorted (ascending):")
print(np.sort(porosity))
print()

print("Indices that would sort permeability:")
print(np.argsort(permeability))
print()

7. ARRAY MANIPULATION
----------------------------------------
Depth array reshaped to column vector (5x1):
[[2500]
 [2510]
 [2520]
 [2530]
 [2540]]

Stacked petrophysical data (Porosity, Permeability, Depth):
[[2.25e+01 1.50e+02 2.50e+03]
 [8.30e+00 5.00e-01 2.51e+03]
 [1.87e+01 4.50e+01 2.52e+03]
 [2.51e+01 3.20e+02 2.53e+03]
 [6.20e+00 2.00e-01 2.54e+03]]

Combined porosity array:
[22.5  8.3 18.7 25.1  6.2 21.  19.5]

Porosity sorted (ascending):
[ 6.2  8.3 18.7 22.5 25.1]

Indices that would sort permeability:
[4 1 2 0 3]

In [ ]:
# --------------------------------------------
# 8. CONDITIONAL OPERATIONS
# --------------------------------------------
print("\n8. CONDITIONAL OPERATIONS")
print("-" * 40)

# np.where - classify reservoir quality
reservoir_quality = np.where(
    (porosity > 15) & (permeability > 50),
    'Good', 'Poor'
)
print("Reservoir quality classification:")
for i in range(len(formations)):
    print(f"  {formations[i]}: {reservoir_quality[i]}")
print()

# np.select - multiple conditions
rock_quality = np.select(
    [
        (porosity >= 20) & (permeability >= 100),
        (porosity >= 15) & (permeability >= 50),
        (porosity < 15) | (permeability < 10)
    ],
    ['Excellent', 'Good', 'Poor'],
    default='Fair'
)
print("Detailed rock quality classification:")
for i in range(len(formations)):
    print(f"  {formations[i]}: {rock_quality[i]} (φ={porosity[i]}%, k={permeability[i]} mD)")
print()

8. CONDITIONAL OPERATIONS
----------------------------------------
Reservoir quality classification:
  Sandstone_A: Good
  Shale_B: Poor
  Limestone_C: Poor
  Sandstone_D: Good
  Shale_E: Poor

Detailed rock quality classification:
  Sandstone_A: Excellent (φ=22.5%, k=150.0 mD)
  Shale_B: Poor (φ=8.3%, k=0.5 mD)
  Limestone_C: Fair (φ=18.7%, k=45.0 mD)
  Sandstone_D: Excellent (φ=25.1%, k=320.0 mD)
  Shale_E: Poor (φ=6.2%, k=0.2 mD)

In [ ]:
# --------------------------------------------
# 9. HANDLING MISSING DATA
# --------------------------------------------
print("\n9. HANDLING MISSING DATA")
print("-" * 40)

# Create array with NaN (Not a Number) for missing log values
porosity_with_nan = np.array([22.5, np.nan, 18.7, 25.1, 6.2])
print("Porosity with missing value (NaN):")
print(porosity_with_nan)
print()

# Check for NaN
print("Which values are NaN?")
print(np.isnan(porosity_with_nan))
print()

# Count NaN values
print(f"Number of missing values: {np.sum(np.isnan(porosity_with_nan))}")
print()

# Calculate statistics ignoring NaN
print(f"Mean porosity (ignoring NaN): {np.nanmean(porosity_with_nan):.2f} %")
print(f"Std dev (ignoring NaN): {np.nanstd(porosity_with_nan):.2f} %")
print()

# Fill NaN with mean value
filled_porosity = np.where(
    np.isnan(porosity_with_nan),
    np.nanmean(porosity_with_nan),
    porosity_with_nan
)
print("Porosity with NaN filled by mean:")
print(filled_porosity)
print()

9. HANDLING MISSING DATA
----------------------------------------
Porosity with missing value (NaN):
[22.5  nan 18.7 25.1  6.2]

Which values are NaN?
[False  True False False False]

Number of missing values: 1

Mean porosity (ignoring NaN): 18.13 %
Std dev (ignoring NaN): 7.25 %

Porosity with NaN filled by mean:
[22.5   18.125 18.7   25.1    6.2  ]

In [ ]:
# --------------------------------------------
# 10. PRACTICAL PETROPHYSICAL CALCULATIONS
# --------------------------------------------
print("\n10. PRACTICAL PETROPHYSICAL CALCULATIONS")
print("-" * 40)

# Calculate Storage Capacity (φ × k)
storage_capacity = porosity * permeability
print("Storage Capacity (φ × k) for each formation:")
for i in range(len(formations)):
    print(f"  {formations[i]}: {storage_capacity[i]:.2f}")
print()

# Calculate Flow Potential (simplified)
# Higher porosity AND permeability = better flow
flow_potential = (porosity / 30) * np.log10(permeability + 0.001)
print("Normalized Flow Potential Index:")
for i in range(len(formations)):
    print(f"  {formations[i]}: {flow_potential[i]:.3f}")
print()

# Identify pay zones (threshold-based)
is_pay_zone = (porosity > 15) & (permeability > 30)
pay_formations = formations[is_pay_zone]
print("Identified Pay Zones (φ > 15% AND k > 30 mD):")
print(pay_formations)
print()

# Calculate average properties for pay zones only
if np.any(is_pay_zone):
    print(f"Average Porosity in Pay Zones: {np.mean(porosity[is_pay_zone]):.2f} %")
    print(f"Average Permeability in Pay Zones: {np.mean(permeability[is_pay_zone]):.2f} mD")
print()

10. PRACTICAL PETROPHYSICAL CALCULATIONS
----------------------------------------
Storage Capacity (φ × k) for each formation:
  Sandstone_A: 3375.00
  Shale_B: 4.15
  Limestone_C: 841.50
  Sandstone_D: 8032.00
  Shale_E: 1.24

Normalized Flow Potential Index:
  Sandstone_A: 1.632
  Shale_B: -0.083
  Limestone_C: 1.031
  Sandstone_D: 2.096
  Shale_E: -0.144

Identified Pay Zones (φ > 15% AND k > 30 mD):
['Sandstone_A' 'Limestone_C' 'Sandstone_D']

Average Porosity in Pay Zones: 22.10 %
Average Permeability in Pay Zones: 171.67 mD

In [ ]:
# --------------------------------------------
# 11. WORKING WITH 2D ARRAYS (MULTI-WELL DATA)
# --------------------------------------------
print("\n11. WORKING WITH 2D ARRAYS")
print("-" * 40)

# Create 2D array: rows = wells, columns = [porosity, permeability]
multi_well_data = np.array([
    [22.5, 150.0],   # Well 1
    [8.3, 0.5],      # Well 2
    [18.7, 45.0],    # Well 3
    [25.1, 320.0],   # Well 4
    [6.2, 0.2]       # Well 5
])
print("Multi-well data [Porosity, Permeability]:")
print(multi_well_data)
print()

# Access specific well
print("Well 4 data (index 3):")
print(f"  Porosity: {multi_well_data[3, 0]} %")
print(f"  Permeability: {multi_well_data[3, 1]} mD")
print()

# Calculate statistics per column (across all wells)
print("Statistics across all wells:")
print(f"  Mean Porosity: {np.mean(multi_well_data[:, 0]):.2f} %")
print(f"  Mean Permeability: {np.mean(multi_well_data[:, 1]):.2f} mD")
print()

# Calculate statistics per row (per well)
well_averages = np.mean(multi_well_data, axis=1)
print("Average property value per well:")
for i, avg in enumerate(well_averages, 1):
    print(f"  Well {i}: {avg:.2f}")
print()

11. WORKING WITH 2D ARRAYS
----------------------------------------
Multi-well data [Porosity, Permeability]:
[[2.25e+01 1.50e+02]
 [8.30e+00 5.00e-01]
 [1.87e+01 4.50e+01]
 [2.51e+01 3.20e+02]
 [6.20e+00 2.00e-01]]

Well 4 data (index 3):
  Porosity: 25.1 %
  Permeability: 320.0 mD

Statistics across all wells:
  Mean Porosity: 16.16 %
  Mean Permeability: 103.14 mD

Average property value per well:
  Well 1: 86.25
  Well 2: 4.40
  Well 3: 31.85
  Well 4: 172.55
  Well 5: 3.20

In [ ]:
# --------------------------------------------
# 12. SAVING AND LOADING NUMPY ARRAYS
# --------------------------------------------
print("\n12. SAVING AND LOADING NUMPY ARRAYS")
print("-" * 40)

# Save single array
np.save('porosity_data.npy', porosity)
print("✓ Saved porosity array to 'porosity_data.npy'")

# Save multiple arrays
np.savez('petro_data.npz',
         porosity=porosity,
         permeability=permeability,
         formations=formations)
print("✓ Saved all arrays to 'petro_data.npz'")

# Load arrays back
loaded_data = np.load('petro_data.npz')
print("\n✓ Loaded data from 'petro_data.npz'")
print(f"  Keys: {list(loaded_data.keys())}")
print(f"  Loaded porosity: {loaded_data['porosity']}")
print()

12. SAVING AND LOADING NUMPY ARRAYS
----------------------------------------
✓ Saved porosity array to 'porosity_data.npy'
✓ Saved all arrays to 'petro_data.npz'

✓ Loaded data from 'petro_data.npz'
  Keys: ['porosity', 'permeability', 'formations']
  Loaded porosity: [22.5  8.3 18.7 25.1  6.2]

In [ ]:

# --------------------------------------------
# 13. QUICK NUMPY CHEAT SHEET
# --------------------------------------------
print("\n13. NUMPY CHEAT SHEET FOR PETROPHYSICS")
print("-" * 40)

cheat_sheet = """
┌────────────────────────────────────────────┐
│         NUMPY QUICK REFERENCE              │
├────────────────────────────────────────────┤
│ CREATING ARRAYS                            │
│   np.array([1, 2, 3])      - From list    │
│   np.zeros(5)              - Array of 0s  │
│   np.ones(5)               - Array of 1s  │
│   np.arange(0, 100, 10)    - Range array  │
│   np.linspace(0, 30, 6)    - Even spacing │
├────────────────────────────────────────────┤
│ ARRAY INFO                                 │
│   arr.shape                - Dimensions   │
│   arr.ndim                 - Num axes     │
│   arr.dtype                - Data type    │
│   arr.size                 - Element count│
├────────────────────────────────────────────┤
│ INDEXING & SLICING                         │
│   arr[0]                   - First element│
│   arr[-1]                  - Last element │
│   arr[1:4]                 - Slice        │
│   arr[arr > 20]            - Boolean filter│
├────────────────────────────────────────────┤
│ MATH OPERATIONS                            │
│   arr + 5, arr * 2         - Element-wise │
│   arr1 / arr2              - Array divide │
│   np.sqrt(arr)             - Square root  │
│   np.log10(arr)            - Log base 10  │
├────────────────────────────────────────────┤
│ STATISTICS                                 │
│   np.mean(arr)             - Average      │
│   np.median(arr)           - Median       │
│   np.std(arr)              - Std deviation│
│   np.min(arr), np.max(arr) - Min/Max      │
│   np.percentile(arr, 50)   - Percentile  │
│   np.nanmean(arr)          - Ignore NaN   │
├────────────────────────────────────────────┤
│ CONDITIONAL                                │
│   np.where(cond, A, B)     - If-else      │
│   np.select(conds, choices) - Multi-if    │
│   (arr1 > x) & (arr2 < y)  - Multiple cond│
├────────────────────────────────────────────┤
│ ARRAY MANIPULATION                         │
│   arr.reshape(5,1)         - Change shape │
│   np.column_stack((a,b))   - Combine cols│
│   np.concatenate((a,b))    - Join arrays  │
│   np.sort(arr)             - Sort values  │
├────────────────────────────────────────────┤
│ SAVE/LOAD                                  │
│   np.save('file.npy', arr) - Save binary │
│   np.load('file.npy')      - Load binary │
│   np.savetxt('file.txt', arr) - Text file│
└────────────────────────────────────────────┘
"""
print(cheat_sheet)

# --------------------------------------------
# FINAL SUMMARY
# --------------------------------------------
print("\n" + "=" * 60)
print("TUTORIAL COMPLETED!")
print("=" * 60)

print("\nWhat you learned:")
print("  1. Create NumPy arrays from lists")
print("  2. Check array properties (shape, dtype, size)")
print("  3. Index and slice arrays")
print("  4. Perform element-wise mathematical operations")
print("  5. Calculate statistics (mean, std, percentiles)")
print("  6. Manipulate arrays (reshape, stack, sort)")
print("  7. Use conditional operations (np.where, np.select)")
print("  8. Handle missing data with NaN")
print("  9. Perform petrophysical calculations")
print("  10. Work with 2D arrays for multi-well data")
print("  11. Save and load NumPy arrays")

print("\n" + "=" * 60)
print("YOUR PETROPHYSICAL DATA SUMMARY:")
print("=" * 60)
print(f"Formations analyzed: {len(formations)}")
print(f"Porosity range: {np.min(porosity)}% - {np.max(porosity)}%")
print(f"Permeability range: {np.min(permeability)} - {np.max(permeability)} mD")
print(f"Average Porosity: {np.mean(porosity):.2f}%")
print(f"Average Permeability: {np.mean(permeability):.2f} mD")
print(f"Pay Zones identified: {np.sum((porosity > 15) & (permeability > 30))}")
print("=" * 60)

print("\nFiles Created:")
print("  • porosity_data.npy")
print("  • petro_data.npz")
print("  • petrophysical_output.txt")
print("=" * 60)

13. NUMPY CHEAT SHEET FOR PETROPHYSICS
----------------------------------------

┌────────────────────────────────────────────┐
│         NUMPY QUICK REFERENCE              │
├────────────────────────────────────────────┤
│ CREATING ARRAYS                            │
│   np.array([1, 2, 3])      - From list    │
│   np.zeros(5)              - Array of 0s  │
│   np.ones(5)               - Array of 1s  │
│   np.arange(0, 100, 10)    - Range array  │
│   np.linspace(0, 30, 6)    - Even spacing │
├────────────────────────────────────────────┤
│ ARRAY INFO                                 │
│   arr.shape                - Dimensions   │
│   arr.ndim                 - Num axes     │
│   arr.dtype                - Data type    │
│   arr.size                 - Element count│
├────────────────────────────────────────────┤
│ INDEXING & SLICING                         │
│   arr[0]                   - First element│
│   arr[-1]                  - Last element │
│   arr[1:4]                 - Slice        │
│   arr[arr > 20]            - Boolean filter│
├────────────────────────────────────────────┤
│ MATH OPERATIONS                            │
│   arr + 5, arr * 2         - Element-wise │
│   arr1 / arr2              - Array divide │
│   np.sqrt(arr)             - Square root  │
│   np.log10(arr)            - Log base 10  │
├────────────────────────────────────────────┤
│ STATISTICS                                 │
│   np.mean(arr)             - Average      │
│   np.median(arr)           - Median       │
│   np.std(arr)              - Std deviation│
│   np.min(arr), np.max(arr) - Min/Max      │
│   np.percentile(arr, 50)   - Percentile  │
│   np.nanmean(arr)          - Ignore NaN   │
├────────────────────────────────────────────┤
│ CONDITIONAL                                │
│   np.where(cond, A, B)     - If-else      │
│   np.select(conds, choices) - Multi-if    │
│   (arr1 > x) & (arr2 < y)  - Multiple cond│
├────────────────────────────────────────────┤
│ ARRAY MANIPULATION                         │
│   arr.reshape(5,1)         - Change shape │
│   np.column_stack((a,b))   - Combine cols│
│   np.concatenate((a,b))    - Join arrays  │
│   np.sort(arr)             - Sort values  │
├────────────────────────────────────────────┤
│ SAVE/LOAD                                  │
│   np.save('file.npy', arr) - Save binary │
│   np.load('file.npy')      - Load binary │
│   np.savetxt('file.txt', arr) - Text file│
└────────────────────────────────────────────┘


============================================================
TUTORIAL COMPLETED!
============================================================

What you learned:
  1. Create NumPy arrays from lists
  2. Check array properties (shape, dtype, size)
  3. Index and slice arrays
  4. Perform element-wise mathematical operations
  5. Calculate statistics (mean, std, percentiles)
  6. Manipulate arrays (reshape, stack, sort)
  7. Use conditional operations (np.where, np.select)
  8. Handle missing data with NaN
  9. Perform petrophysical calculations
  10. Work with 2D arrays for multi-well data
  11. Save and load NumPy arrays

============================================================
YOUR PETROPHYSICAL DATA SUMMARY:
============================================================
Formations analyzed: 5
Porosity range: 6.2% - 25.1%
Permeability range: 0.2 - 320.0 mD
Average Porosity: 16.16%
Average Permeability: 103.14 mD
Pay Zones identified: 3
============================================================

Files Created:
  • porosity_data.npy
  • petro_data.npz
  • petrophysical_output.txt
============================================================